(function (d) {
  const l = (d["ko"] = d["ko"] || {});
  l.dictionary = Object.assign(l.dictionary || {}, {
    "Block quote": "인용 단락",
    Bold: "굵게",
    "Bulleted List": "글머리기호",
    Cancel: "취소",
    "Cannot upload file:": "파일 업로드 불가",
    "Centered image": "가운데 정렬",
    "Change image text alternative": "대체 텍스트 변경",
    "Choose heading": "제목 선택",
    Downloadable: "다운로드 가능",
    "Edit link": "링크 수정",
    "Enter image caption": "이미지 설명을 입력하세요",
    "Full size image": "전체 너비",
    Heading: "문단 서식",
    "Heading 1": "제목1",
    "Heading 2": "제목2",
    "Heading 3": "제목3",
    "Heading 4": "제목4",
    "Heading 5": "제목5",
    "Heading 6": "제목6",
    "Image toolbar": "이미지 툴바",
    "image widget": "이미지 위젯",
    "Insert image": "이미지 삽입",
    Italic: "기울임꼴",
    "Left aligned image": "왼쪽 정렬",
    Link: "링크",
    "Link URL": "링크 주소",
    "Numbered List": "번호매기기",
    "Open in a new tab": "새 탭에서 열기",
    "Open link in new tab": "새 탭에서 링크 열기",
    Paragraph: "문단",
    Redo: "다시 실행",
    "Right aligned image": "오른쪽 정렬",
    Save: "저장",
    "Side image": "내부 우측 정렬",
    "Text alternative": "대체 텍스트",
    "This link has no URL": "이 링크는 URL이 아닙니다.",
    Undo: "실행 취소",
    Unlink: "링크 삭제",
    "Upload failed": "업로드 실패",
    "Decrease indent": "내어쓰기",
    "Increase indent": "들여쓰기",
    "Media toolbar": "미디어 툴바",
    "Table toolbar": "테이블 툴바",
    "%0 of %1": "%0 of %1",
    Aquamarine: "연한 청록색",
    Big: "큰",
    Black: "검정색",
    Blue: "파랑",
    Column: "열",
    Default: "기본",
    "Delete column": "열 삭제",
    "Delete row": "행 삭제",
    "Dim grey": "진한 회색",
    "Document colors": "문서 색상들",
    "Dropdown toolbar": "드롭다운 툴바",
    "Editor toolbar": "에디터 툴바",
    "Font Background Color": "글자 배경색",
    "Font Color": "글자 색상",
    "Font Family": "글꼴",
    "Font Size": "글자 크기",
    Green: "초록색",
    Grey: "회색",
    "Header column": "헤더 열 지정",
    "Header row": "헤더 행 지정",
    Huge: "아주 큰",
    "Insert column left": "열 왼쪽 삽입",
    "Insert column right": "열 오른쪽 삽입",
    "Insert media": "미디어 삽입",
    "Insert row above": "행 위로 삽입",
    "Insert row below": "행 아래로 삽입",
    "Insert table": "테이블 삽입",
    "Light blue": "연한 파랑",
    "Light green": "연한 초록",
    "Light grey": "연한 회색",
    "Media URL": "미디어 URL",
    "media widget": "미디어 위젯",
    "Merge cell down": "셀 아래로 병합",
    "Merge cell left": "셀 왼쪽으로 병합",
    "Merge cell right": "셀 오른쪽으로 병합",
    "Merge cell up": "셀 위로 병합",
    "Merge cells": "셀 병합",
    Next: "다음",
    Orange: "주황",
    "Paste the media URL in the input.": "여기에 미디어 URL을 입력하세요.",
    Previous: "이전",
    Purple: "보라",
    Red: "빨강",
    "Rich Text Editor": "Rich Text Editor",
    "Rich Text Editor, %0": "Rich Text Editor, %0",
    Row: "행",
    "Select all": "전체 선택",
    "Select column": "열 선택",
    "Select row": "행 선택",
    "Show more items": "더보기",
    Small: "작은",
    "Split cell horizontally": "셀 수평 분할",
    "Split cell vertically": "셀 수직 분할",
    "The URL must not be empty.": "URL이 비어있습니다.",
    "This media URL is not supported.": "지원되지 않는 URL 입니다.",
    Tiny: "작은",
    "Tip: Paste the URL into the content to embed faster.":
      "팁: URL을 복사+붙여넣기 하면 빠릅니다.",
    Turquoise: "청록색",
    "Upload in progress": "업로드 중",
    White: "흰색",
    "Widget toolbar": "위젯 툴바",
    Yellow: "노랑",
    "Full size media": "전체 너비",
    "Left aligned media": "왼쪽 정렬",
    "Centered media": "가운데 정렬",
    "Right aligned media": "오른쪽 정렬",
  });
  l.getPluralForm = function (n) {
    return 0;
  };
})(window.CKEDITOR_TRANSLATIONS || (window.CKEDITOR_TRANSLATIONS = {}));
